- name: Remove apache2
  apt: name=apache2 state=absent

- name: Install nginx
  action: apt pkg={{ item }} state=installed
  with_items:
   - nginx
   - nginx-extras

- name: Create global nginx configs dir
  file: path=/etc/nginx/global state=directory

- name: write the static asset caching nginx addon
  copy: src=nginx/global/static-asset-caching.conf dest=/etc/nginx/global/static-asset-caching.conf
  notify:
  - nginx restart

- name: write the nginx config files
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - nginx restart

- name: write sample nginx app config file
  template: src=example.conf.j2 dest=/etc/nginx/sites-available/example.conf

- name: start nginx
  service: name=nginx state=started
