---
- hosts: all
  sudo: yes
  remote_user: root
  vars_files:
    - vars/config.yml
  roles:
    - bootstrap

- hosts: all
  sudo: yes
  vars_files:
    - vars/config.yml
  remote_user: "{{sysadmin.username}}"
  roles:
    - common
    - ruby
    - nginx-passenger
    - deploy-conf
    - postgres
