- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf
  notify:
  - restart postgresql

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf
  notify:
  - restart postgresql

- name: ensure database is created
  postgresql_db: name={{app_name}}
  become: true
  become_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{app_name}} name={{postgres.username}} password={{postgres.password}} priv=ALL
  become: true
  become_user: postgres
